HOST=0.0.0.0
PORT=1337
APP_KEYS=FfxZLWNXMG6K8gRe/GUNsg==,NsdNV8LKVo2i8RuQeNYTpg==,Y7VctI60DvxQLB7hmXbxlA==,HtH7e0DxZZrbmwVmcZr0gA==
API_TOKEN_SALT=pHTu3JRNyM6H8ZHZwoQwSw==
ADMIN_JWT_SECRET=GnSD+7KKkIL/t3sF4GjWpA==
TRANSFER_TOKEN_SALT=6rqEKiU4QLKVEbM98Gg4og==
# Database using sqllite -----
#DATABASE_CLIENT=sqlite
#DATABASE_FILENAME=.tmp/data.db
# Database using postgres -----
DATABASE_CLIENT=postgres
DATABASE_HOST=${STRAPI_DATABASE_HOST}
DATABASE_PORT=${STRAPI_DATABASE_PORT}
DATABASE_NAME=${STRAPI_DATABASE_NAME}
DATABASE_USERNAME=${STRAPI_DATABASE_USERNAME}
DATABASE_PASSWORD=${STRAPI_DATABASE_PASSWORD}
DATABASE_SCHEMA=${STRAPI_DATABASE_SCHEMA}
JWT_SECRET=+vKJyaOMrA8x5jnJrULwFQ==
AWS_ACCESS_KEY_ID=${STRAPI_S3_ACCESS_KEY_ID}
AWS_ACCESS_SECRET=${STRAPI_S3_ACCESS_SECRET_ID}
AWS_REGION=${AWS_REGION}
AWS_BUCKET=${STRAPI_S3_BUCKET_NAME}
